# Generated by Django 4.2.6 on 2023-10-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('host_id', models.IntegerField(default=1)),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('event_title', models.CharField(blank=True, max_length=255, null=True)),
                ('event_num_participants', models.IntegerField()),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('event_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('event_language', models.CharField(blank=True, max_length=255, null=True)),
                ('event_price', models.IntegerField(default=0)),
                ('event_location', models.CharField(blank=True, max_length=255, null=True)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_num_joined', models.IntegerField(default=0)),
            ],
        ),
    ]
