# Generated by Django 4.2.6 on 2023-10-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('thumbnail', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('number_of_people', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('language', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to='users.user')),
            ],
        ),
    ]
