# Generated by Django 4.2.7 on 2023-11-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_register_date_event_event_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host_id',
            field=models.IntegerField(default=1),
        ),
    ]
