# Generated by Django 4.2.6 on 2023-11-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_host_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_images',
            field=models.ImageField(blank=True, null=True, upload_to='event_image/'),
        ),
    ]
