# Generated by Django 4.2.7 on 2023-11-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField(default=0)),
                ('host_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('request_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
