# Generated by Django 4.2.7 on 2023-11-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
