# Generated by Django 4.2.7 on 2023-11-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='contact',
            new_name='applicant_contact',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='user_id',
            new_name='applicant_id',
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
