# Generated by Django 4.2.7 on 2023-11-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_rename_contact_application_applicant_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
