# Generated by Django 4.2.6 on 2023-12-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_applicant_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_contact',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True),
        ),
    ]
